CREATE DATABASE blog_crud;

USE blog_crud;

CREATE TABLE posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL
);

/
/
SQL Query
ALTER TABLE posts
CHANGE COLUMN id post_id INT AUTO_INCREMENT;

ALTER TABLE posts
ADD COLUMN date DATE DEFAULT NULL,
ADD COLUMN created_id INT,
ADD COLUMN updated_id INT;

CREATE TABLE Users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20),
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE posts DROP COLUMN created_id, DROP COLUMN updated_id;

ALTER TABLE users DROP COLUMN created_at, DROP COLUMN updated_at;

ALTER TABLE posts
ADD COLUMN user_id INT,
ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (user_id);